#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=7.76.1
fetch_web "https://curl.haxx.se/download/curl-$pkgver.tar.bz2" \
	7a8e184d7d31312c4ebf6a8cb59cd757e61b2b2833a9ed4f9bf708066e7695e9
unpack_tar "curl-$pkgver.tar.bz2" --strip-components=1

CC=$MINGW_CC ./configure --host=$MINGW_PREFIX --prefix=/ \
	--enable-ipv6 --with-winssl --disable-ldap \
	--with-zlib=$(depend_get_path zlib)
make

make DESTDIR=$INSTALL_DIR install
rm -f $INSTALL_DIR/bin/curl-config
common_tidy

package $pkgver
