#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=2.13.2
fetch_web "https://download.savannah.gnu.org/releases/freetype/freetype-$pkgver.tar.gz" \
	1ac27e16c134a7f2ccea177faba19801131116fd682efc1f5737037c5db224b5
unpack_tar "freetype-$pkgver.tar.gz" --strip-components=1

zlibpath=$(depend_get_path zlib)
mkdir -p cmakebuild
cd cmakebuild
cmake .. -DCMAKE_TOOLCHAIN_FILE="$CMAKE_TOOLCHAIN" \
	-DFT_REQUIRE_ZLIB=ON \
	-DZLIB_INCLUDE_DIR="$zlibpath/include" -DZLIB_LIBRARY="$zlibpath/lib/libz.dll.a"
make

common_flat_tree
make DESTDIR=$INSTALL_DIR install
common_tidy

package $pkgver
