#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=2.12.1
fetch_web "https://download.savannah.gnu.org/releases/freetype/freetype-$pkgver.tar.gz" \
	efe71fd4b8246f1b0b1b9bfca13cfff1c9ad85930340c27df469733bbb620938
unpack_tar "freetype-$pkgver.tar.gz" --strip-components=1

PKG_CONFIG=/bin/false PYTHON=missing \
./configure --host=$MINGW_PREFIX --prefix=/ --with-png=no
make

make DESTDIR=$INSTALL_DIR install
common_tidy

package $pkgver
