#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=2.13.2
fetch_web "https://download.savannah.gnu.org/releases/freetype/freetype-$pkgver.tar.gz" \
	1ac27e16c134a7f2ccea177faba19801131116fd682efc1f5737037c5db224b5
unpack_tar "freetype-$pkgver.tar.gz" --strip-components=1

PKG_CONFIG=/bin/false PYTHON=missing \
./configure --host=$MINGW_PREFIX --prefix=/ --with-png=no
make

make DESTDIR=$INSTALL_DIR install
common_tidy

package $pkgver
