#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=2.11.1
fetch_web "https://download.savannah.gnu.org/releases/freetype/freetype-$pkgver.tar.gz" \
	f8db94d307e9c54961b39a1cc799a67d46681480696ed72ecf78d4473770f09b
unpack_tar "freetype-$pkgver.tar.gz" --strip-components=1

PKG_CONFIG=/bin/false PYTHON=missing \
./configure --host=$MINGW_PREFIX --prefix=/ --with-png=no
make

make DESTDIR=$INSTALL_DIR install
common_tidy

package $pkgver
