#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=2.13.3
fetch_web "https://download.savannah.gnu.org/releases/freetype/freetype-$pkgver.tar.gz" \
	5c3a8e78f7b24c20b25b54ee575d6daa40007a5f4eea2845861c3409b3021747
unpack_tar "freetype-$pkgver.tar.gz" --strip-components=1

zlibpath=$(depend_get_path zlib)
mkdir -p cmakebuild
cd cmakebuild
cmake .. -DCMAKE_TOOLCHAIN_FILE="$CMAKE_TOOLCHAIN" \
	-DBUILD_SHARED_LIBS=ON -DFT_REQUIRE_ZLIB=ON \
	-DZLIB_INCLUDE_DIR="$zlibpath/include" -DZLIB_LIBRARY="$zlibpath/lib/libz.dll.a"
make

common_flat_tree
make DESTDIR=$INSTALL_DIR install
common_tidy

package $pkgver
