#!/bin/bash -eu

. ./common.sh
CUSTOMOPTS[0]="all-tools|alltools|Keep all installed gettext tools"
common_init "$@"

# this is a joint package which includes both libiconv and gettext
iconvver=1.16
intlver=0.20.1
mkdir -p iconv intl
fetch_web "https://ftp.gnu.org/pub/gnu/libiconv/libiconv-$iconvver.tar.gz" \
	e6a1b1b589654277ee790cce3734f07876ac4ccfaecbee8afa0b649cf529cc04
fetch_web "https://ftp.gnu.org/gnu/gettext/gettext-$intlver.tar.xz" \
	53f02fbbec9e798b0faaf7c73272f83608e835c6288dd58be6c9bb54624a3800
unpack_tar "libiconv-$iconvver.tar.gz" -C iconv --strip-components=1
unpack_tar "gettext-$intlver.tar.xz" -C intl --strip-components=1

pushd iconv
./configure --host=$MINGW_PREFIX --prefix=/ \
	--enable-{static,shared} \
	--disable-{rpath,nls}
make
make DESTDIR=$INSTALL_DIR install
popd
#
pushd intl
# gettext really REALLY does not like crosscompiling (also GNU is retarded)
for dir in gettext-runtime libtextstyle gettext-tools .; do
	sed -r 's|^(\s*cross_compiling).*|\1=yes|' -i $dir/configure
done
sed 's/HAVE_FWPRINTF/HAVE_WPRINTF/g' -i gettext-runtime/intl/printf.c
CPPFLAGS="-I$INSTALL_DIR/include" LDFLAGS="-L$INSTALL_DIR/lib" LIBS="-liconv" \
./configure --host=$MINGW_PREFIX --prefix=/fuckoff \
	--enable-{static,shared} \
	--disable-{java,rpath,libasprintf,curses} --enable-relocatable \
	--with-included-{gettext,libunistring,libxml}
make
popd

# (iconv is already installed)
pushd intl
ln -s . $INSTALL_DIR/fuckoff
make DESTDIR=$INSTALL_DIR install
rm $INSTALL_DIR/fuckoff
popd
#
common_tidy
rm -rf $INSTALL_DIR/lib/{gettext,*.dll} $INSTALL_DIR/share
if [ $alltools -eq 0 ]; then
	mv $INSTALL_DIR/{bin,bin.old}; mkdir -p $INSTALL_DIR/bin
	cp -p $INSTALL_DIR/bin.old/{*.dll,iconv.exe,msgfmt.exe} $INSTALL_DIR/bin
	rm -rf $INSTALL_DIR/bin.old
fi

package $intlver
