#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=master
fetch_git https://github.com/minetest/irrlicht $pkgver

pngpath=$(depend_get_path libpng)
jpegpath=$(depend_get_path libjpeg)
zlibpath=$(depend_get_path zlib)
cmake . -DCMAKE_TOOLCHAIN_FILE="$CMAKE_TOOLCHAIN" \
	-DPNG_LIBRARY=$pngpath/lib/libpng.dll.a \
	-DPNG_PNG_INCLUDE_DIR=$pngpath/include \
	-DJPEG_LIBRARY=$jpegpath/lib/libjpeg.dll.a \
	-DJPEG_INCLUDE_DIR=$jpegpath/include \
	-DZLIB_LIBRARY=$zlibpath/lib/libz.dll.a \
	-DZLIB_INCLUDE_DIR=$zlibpath/include
make

common_flat_tree
make DESTDIR=$INSTALL_DIR install
mkdir -p $INSTALL_DIR/bin
mv $INSTALL_DIR/lib/*.dll $INSTALL_DIR/bin
common_tidy

package $pkgver
