#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=1.8.4
# URL specifies a mirror because some SF mirrors are beyond slow (~ 10 KB/s)
fetch_web "http://downloads.sourceforge.net/irrlicht/irrlicht-$pkgver.zip?use_mirror=netcologne" \
	f42b280bc608e545b820206fe2a999c55f290de5c7509a02bdbeeccc1bf9e433 irrlicht-$pkgver.zip
unpack_zip irrlicht-$pkgver.zip

cd irrlicht-$pkgver
buildid=Win32-gcc
# enable Direct3D9 support
sed -r '/-DNO_IRR_COMPILE_WITH_DIRECT3D_9_/ s/^/#/
	/^sharedlib_win32: LDFLAGS/ s/-ld3dx9d/-ld3dx9_43 -ldinput8 -ldxguid/' \
	-i source/Irrlicht/Makefile
sed 's/defined(IRR_COMPILE_WITH_DX9_DEV_PACK)/1/' \
	-i include/IrrCompileConfig.h
# modify makefile for 64-bit gcc build
if [ "$MINGW_TYPE" = "win64" ]; then
	sed 's/Win32-gcc/Win64-gcc/g' -i source/Irrlicht/Makefile
	buildid=Win64-gcc
	mkdir -p {bin,lib}/Win64-gcc
	cp bin/Win32-gcc/irrlicht.ico bin/Win64-gcc
fi
commonopts="CC=$MINGW_CC CXX=$MINGW_CXX NDEBUG=1"
# build shared lib
make -Csource/Irrlicht $commonopts sharedlib_win32
# preserve the implib (.dll.a) and clean
mv lib/$buildid/libIrrlicht{.a,.dll.a}
make -Csource/Irrlicht clean
# build static lib
make -Csource/Irrlicht $commonopts staticlib_win32

mkdir -p $INSTALL_DIR/{bin/$buildid,lib}
cp -r include $INSTALL_DIR
cp -r bin/$buildid/*.{dll,ico} $INSTALL_DIR/bin/$buildid
cp -r lib/$buildid $INSTALL_DIR/lib

package $pkgver
