#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=2.3.3
fetch_web "https://github.com/libgd/libgd/releases/download/gd-$pkgver/libgd-$pkgver.tar.xz" \
	3fe822ece20796060af63b7c60acb151e5844204d289da0ce08f8fdf131e5a61
unpack_tar "libgd-$pkgver.tar.xz" --strip-components=1

sed 's|SET[(]GD_LIB libgd[)]|set(GD_LIB gd)|' -i CMakeLists.txt # ?!
zlibpath=$(depend_get_path zlib)
pngpath=$(depend_get_path libpng)
cmake . -DCMAKE_TOOLCHAIN_FILE="$CMAKE_TOOLCHAIN" \
	-DBUILD_STATIC_LIBS=1 -DENABLE_PNG=1 \
	-DPNG_LIBRARY=$pngpath/lib/libpng16.dll.a \
	-DPNG_PNG_INCLUDE_DIR=$pngpath/include \
	-DZLIB_LIBRARY=$zlibpath/lib/libz.dll.a \
	-DZLIB_INCLUDE_DIR=$zlibpath/include
make

common_flat_tree
make DESTDIR=$INSTALL_DIR install
rm -f $INSTALL_DIR/bin/{*.exe,bdftogd} # remove obscure utilities
common_tidy

package $pkgver
