#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=2.3.2
fetch_web "https://github.com/libgd/libgd/releases/download/gd-$pkgver/libgd-$pkgver.tar.xz" \
	478a047084e0d89b83616e4c2cf3c9438175fb0cc55d8c8967f06e0427f7d7fb
unpack_tar "libgd-$pkgver.tar.xz" --strip-components=1

sed 's|SET[(]GD_LIB libgd[)]|set(GD_LIB gd)|' -i CMakeLists.txt # ?!
zlibpath=$(depend_get_path zlib)
pngpath=$(depend_get_path libpng)
cmake . -DCMAKE_TOOLCHAIN_FILE="$CMAKE_TOOLCHAIN" \
	-DBUILD_STATIC_LIBS=1 -DENABLE_PNG=1 \
	-DPNG_LIBRARY=$pngpath/lib/libpng.dll.a \
	-DPNG_PNG_INCLUDE_DIR=$pngpath/include \
	-DZLIB_LIBRARY=$zlibpath/lib/libz.dll.a \
	-DZLIB_INCLUDE_DIR=$zlibpath/include
make

common_flat_tree
make DESTDIR=$INSTALL_DIR install
rm -f $INSTALL_DIR/bin/{*.exe,bdftogd} # remove obscure utilities
common_tidy

package $pkgver
