#!/bin/bash -eu

. ./common.sh
common_init "$@"

which nasm >/dev/null || which yasm >/dev/null || \
	{ echo >&2 "A standalone assembler is required for this build."; exit 1; }

pkgver=2.1.5.1
fetch_web "https://downloads.sourceforge.net/libjpeg-turbo/libjpeg-turbo-${pkgver}.tar.gz" \
	2fdc3feb6e9deb17adec9bafa3321419aa19f8f4e5dea7bf8486844ca22207bf
unpack_tar "libjpeg-turbo-${pkgver}.tar.gz" --strip-components=1

cmake . -DCMAKE_TOOLCHAIN_FILE="$CMAKE_TOOLCHAIN" -DCMAKE_INSTALL_PREFIX=/ \
	-DCMAKE_SYSTEM_PROCESSOR=${MINGW_PREFIX%%-*}
make

common_flat_tree
make DESTDIR=$INSTALL_DIR install
rm -f $INSTALL_DIR/bin/*.exe
common_tidy

package $pkgver
