#!/bin/bash -eu

. ./common.sh
common_init "$@"

fetch_git https://github.com/google/leveldb 1.21

# build shared lib
cmake . \
	-DCMAKE_SYSTEM_NAME=Windows \
	-DCMAKE_C_COMPILER=$MINGW_CC \
	-DCMAKE_CXX_COMPILER=$MINGW_CXX \
	-DBUILD_SHARED_LIBS=YES -DLEVELDB_BUILD_TESTS=NO
make leveldb

# build static lib
cmake . -DBUILD_SHARED_LIBS=NO
make leveldb

mkdir -p $INSTALL_DIR/{bin,lib,include}
cp -r include/leveldb $INSTALL_DIR/include
cp libleveldb.dll $INSTALL_DIR/bin
cp libleveldb.a $INSTALL_DIR/lib
cp libleveldb.dll.a $INSTALL_DIR/lib

major=$(sed -rn 's/.*int kMajorVersion = ([0-9]+);$/\1/p' include/leveldb/db.h)
minor=$(sed -rn 's/.*int kMinorVersion = ([0-9]+);$/\1/p' include/leveldb/db.h)
package $major.$minor
