#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=1.22
fetch_git https://github.com/google/leveldb $pkgver

# build shared lib
cmake . -DCMAKE_TOOLCHAIN_FILE="$CMAKE_TOOLCHAIN" \
	-DBUILD_SHARED_LIBS=YES -DLEVELDB_BUILD_TESTS=NO
make leveldb

# build static lib
cmake . -DBUILD_SHARED_LIBS=NO
make leveldb

mkdir -p $INSTALL_DIR/{bin,lib,include}
cp -r include/leveldb $INSTALL_DIR/include
cp libleveldb.dll $INSTALL_DIR/bin
cp libleveldb.a $INSTALL_DIR/lib
cp libleveldb.dll.a $INSTALL_DIR/lib

package $pkgver
