#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=1.3.5
fetch_web "http://downloads.xiph.org/releases/ogg/libogg-$pkgver.tar.xz" \
	c4d91be36fc8e54deae7575241e03f4211eb102afb3fc0775fbbc1b740016705
unpack_tar "libogg-$pkgver.tar.xz" --strip-components=1

./configure --host=$MINGW_PREFIX --prefix=/
make

make DESTDIR=$INSTALL_DIR install
common_tidy

package $pkgver
