#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=1.3.4
fetch_web "http://downloads.xiph.org/releases/ogg/libogg-$pkgver.tar.xz" \
	c163bc12bc300c401b6aa35907ac682671ea376f13ae0969a220f7ddf71893fe
unpack_tar "libogg-$pkgver.tar.xz" --strip-components=1

./configure --host=$MINGW_PREFIX --prefix=/
make

make DESTDIR=$INSTALL_DIR install
common_tidy

package $pkgver
