#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=1.6.40
fetch_web "https://downloads.sourceforge.net/sourceforge/libpng/libpng-$pkgver.tar.xz" \
	535b479b2467ff231a3ec6d92a525906fb8ef27978be4f66dbe05d3f3a01b3a1
unpack_tar "libpng-$pkgver.tar.xz" --strip-components=1

zlibpath=$(depend_get_path zlib)
cmake . -DCMAKE_TOOLCHAIN_FILE="$CMAKE_TOOLCHAIN" \
	-DZLIB_LIBRARY=$zlibpath/lib/libz.dll.a \
	-DZLIB_INCLUDE_DIR=$zlibpath/include
make

common_flat_tree
make DESTDIR=$INSTALL_DIR install
rm -f $INSTALL_DIR/bin/*-config
common_tidy

package $pkgver
