#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=1.6.43
fetch_web "https://downloads.sourceforge.net/sourceforge/libpng/libpng-$pkgver.tar.xz" \
	6a5ca0652392a2d7c9db2ae5b40210843c0bbc081cbd410825ab00cc59f14a6c
unpack_tar "libpng-$pkgver.tar.xz" --strip-components=1

zlibpath=$(depend_get_path zlib)
cmake . -DCMAKE_TOOLCHAIN_FILE="$CMAKE_TOOLCHAIN" \
	-DZLIB_LIBRARY=$zlibpath/lib/libz.dll.a \
	-DZLIB_INCLUDE_DIR=$zlibpath/include
make

common_flat_tree
make DESTDIR=$INSTALL_DIR install
rm -f $INSTALL_DIR/bin/*-config
common_tidy

package $pkgver
