#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=1.6.37
fetch_web "https://downloads.sourceforge.net/sourceforge/libpng/libpng-$pkgver.tar.xz" \
	505e70834d35383537b6491e7ae8641f1a4bed1876dbfe361201fc80868d88ca
unpack_tar "libpng-$pkgver.tar.xz" --strip-components=1

zlibpath=$(depend_get_path zlib)
CFLAGS=-I$zlibpath/include LDFLAGS="-L$zlibpath/lib -lwinpthread" \
./configure --host=$MINGW_PREFIX --prefix=/
sed '/^#am__append_9/ s|.*|am__append_9 = $(CFLAGS)|' -i Makefile
make

make DESTDIR=$INSTALL_DIR install
common_tidy

package $pkgver
