#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=1.3.7
fetch_web "http://downloads.xiph.org/releases/vorbis/libvorbis-$pkgver.tar.xz" \
	b33cc4934322bcbf6efcbacf49e3ca01aadbea4114ec9589d1b1e9d20f72954b
unpack_tar "libvorbis-$pkgver.tar.xz" --strip-components=1

oggpath=$(depend_get_path libogg)
OGG_CFLAGS="-I$oggpath/include" OGG_LIBS="-L$oggpath/lib -logg" \
./configure --host=$MINGW_PREFIX --prefix=/
make

make DESTDIR=$INSTALL_DIR install
common_tidy

package $pkgver
