#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=1.3.7
fetch_web "http://downloads.xiph.org/releases/vorbis/libvorbis-$pkgver.tar.xz" \
	b33cc4934322bcbf6efcbacf49e3ca01aadbea4114ec9589d1b1e9d20f72954b
unpack_tar "libvorbis-$pkgver.tar.xz" --strip-components=1

oggpath=$(depend_get_path libogg)
cmake . -DCMAKE_TOOLCHAIN_FILE="$CMAKE_TOOLCHAIN" \
	-DBUILD_SHARED_LIBS=ON -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
	-DOGG_INCLUDE_DIR="$oggpath/include" -DOGG_LIBRARY="$oggpath/lib/libogg.dll.a"
make

common_flat_tree
make DESTDIR=$INSTALL_DIR install
# can't move DLL since .cmake file references them
common_tidy

package $pkgver
