#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=1.3.5
fetch_web "http://downloads.xiph.org/releases/vorbis/libvorbis-$pkgver.tar.xz" \
	54f94a9527ff0a88477be0a71c0bab09a4c3febe0ed878b24824906cd4b0e1d1
unpack_tar "libvorbis-$pkgver.tar.xz" --strip-components=1

oggpath=$(depend_get_path libogg)
CC=$MINGW_CC \
OGG_CFLAGS=-I$oggpath/include OGG_LIBS="-L$oggpath/lib -logg" \
./configure --host=${MINGW_CC%-*} --prefix=/
make -j$MAKE_JOBS

make DESTDIR=$INSTALL_DIR install
rm -rf $INSTALL_DIR/{share,lib/*.la,lib/pkgconfig} # no docs or pkg-config on windows

package $pkgver