#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=1.11.4
fetch_web "https://libzip.org/download/libzip-$pkgver.tar.gz" \
	82e9f2f2421f9d7c2466bbc3173cd09595a88ea37db0d559a9d0a2dc60dc722e
unpack_tar "libzip-$pkgver.tar.gz" --strip-components=1

zlibpath=$(depend_get_path zlib)
cmake . "${CMAKE_FLAGS[@]}" \
	-DZLIB_LIBRARY=$zlibpath/lib/libz.dll.a \
	-DZLIB_INCLUDE_DIR=$zlibpath/include \
	-DBUILD_{EXAMPLES,OSSFUZZ,REGRESS}=OFF -DENABLE_{BZIP2,LZMA,ZSTD}=OFF
make

common_flat_tree
make DESTDIR=$INSTALL_DIR install
common_tidy

package $pkgver
