#!/bin/bash -eu

. ./common.sh
common_init "$@"

# LuaJIT is rolling-release
pkgver=20251206
pkgver_commit=45b771bb2c693a4cc7e34e79b7d30ab10bb7776a
fetch_git https://github.com/LuaJIT/LuaJIT
git checkout -q $pkgver_commit

extra=-m${MINGW_TYPE#win}
make \
	HOST_CC="cc $extra" BUILDMODE=static \
	CROSS=$MINGW_PREFIX- TARGET_SYS=Windows \
	amalg

# different package structure for ... historical reasons
mkdir -p $INSTALL_DIR/include
cp src/*.h $INSTALL_DIR/include
cp src/luajit.exe src/libluajit.a $INSTALL_DIR

package $pkgver
