#!/bin/bash -eu

. ./common.sh
common_init "$@"

# LuaJIT no longer provides any releases/tags
pkgver=20250113
pkgver_commit=a4f56a459a588ae768801074b46ba0adcfb49eb1
fetch_git https://github.com/LuaJIT/LuaJIT
git checkout -q $pkgver_commit

extra=-m${MINGW_TYPE#win}
make \
	HOST_CC="cc $extra" BUILDMODE=static \
	CROSS=$MINGW_PREFIX- TARGET_SYS=Windows \
	amalg

# different package structure for ... historical reasons
mkdir -p $INSTALL_DIR/include
cp src/*.h $INSTALL_DIR/include
cp src/luajit.exe src/libluajit.a $INSTALL_DIR

package $pkgver
