#!/bin/bash -eu

. ./common.sh
common_init "$@"

# LuaJIT is rolling-release
pkgver=20260304
pkgver_commit=89f268b3f745dba80da6350d3cbbb0964f3fdbee
fetch_git https://github.com/LuaJIT/LuaJIT
git checkout -q $pkgver_commit

extra=
[ "$MINGW_TYPE" = win32 ] && extra=-m32
make \
	HOST_CC="cc $extra" BUILDMODE=static \
	CROSS=$MINGW_PREFIX- TARGET_SYS=Windows \
	amalg

# different package structure for ... historical reasons
mkdir -p $INSTALL_DIR/include
cp src/*.h $INSTALL_DIR/include
cp src/luajit.exe src/libluajit.a $INSTALL_DIR

package $pkgver
