#!/bin/bash -eu

. ./common.sh
common_init "$@"

pushargs () {
	local replace=$1
	shift
	for arg in "$@"; do
		# replace $ as a placeholder
		[[ "$1" == *"$"* ]] && \
			arg=${arg%%\$*}${replace}${arg#*$}
		cmake_args+=("$arg")
	done
}

# meant for compile testing, does not install anything usable
pkgver=master
fetch_git https://github.com/luanti-org/luanti $pkgver

cmake_args=()
pushargs "$(depend_get_path libpng)" \
	-DPNG_PNG_INCLUDE_DIR='$/include' \
	-DPNG_LIBRARY='$/lib/libpng16.dll.a' \
	-DPNG_DLL='$/bin/libpng16.dll'
pushargs "$(depend_get_path libjpeg)" \
	-DJPEG_LIBRARY='$/lib/libjpeg.dll.a' \
	-DJPEG_INCLUDE_DIR='$/include' \
	-DJPEG_DLL='$/bin/libjpeg-62.dll'
pushargs "$(depend_get_path sdl2)" \
	-DCMAKE_PREFIX_PATH='$/lib/cmake'
pushargs "$(depend_get_path zlib)" \
	-DZLIB_INCLUDE_DIR='$/include' \
	-DZLIB_LIBRARY='$/lib/libz.dll.a' \
	-DZLIB_DLL='$/bin/zlib1.dll'
pushargs "$(depend_get_path luajit)" \
	-DLUA_INCLUDE_DIR='$/include' \
	-DLUA_LIBRARY='$/libluajit.a'
pushargs "$(depend_get_path curl)" \
	-DCURL_INCLUDE_DIR='$/include' \
	-DCURL_LIBRARY='$/lib/libcurl.dll.a' \
	-DCURL_DLL='$/bin/libcurl-4.dll'
pushargs "$(depend_get_path freetype)" \
	-DFREETYPE_INCLUDE_DIR_{freetype2,ft2build}='$/include/freetype2' \
	-DFREETYPE_LIBRARY='$/lib/libfreetype.dll.a' \
	-DFREETYPE_DLL='$/bin/libfreetype-6.dll'
pushargs "$(depend_get_path sqlite3)" \
	-DSQLITE3_INCLUDE_DIR='$/include' \
	-DSQLITE3_LIBRARY='$/lib/libsqlite3.dll.a' \
	-DSQLITE3_DLL='$/bin/libsqlite3-0.dll'
pushargs "$(depend_get_path libleveldb)" \
	-DLEVELDB_INCLUDE_DIR='$/include' \
	-DLEVELDB_LIBRARY='$/lib/libleveldb.dll.a' \
	-DLEVELDB_DLL='$/bin/libleveldb.dll'
pushargs "$(depend_get_path openal-soft)" \
	-DOPENAL_INCLUDE_DIR='$/include/AL' \
	-DOPENAL_LIBRARY='$/lib/libOpenAL32.dll.a' \
	-DOPENAL_DLL='$/bin/OpenAL32.dll'
pushargs "$(depend_get_path libogg)" \
	-DOGG_INCLUDE_DIR='$/include' \
	-DOGG_LIBRARY='$/lib/libogg.dll.a' \
	-DOGG_DLL='$/bin/libogg-0.dll'
pushargs "$(depend_get_path libvorbis)" \
	-DVORBIS_INCLUDE_DIR='$/include' \
	-DVORBIS_LIBRARY='$/lib/libvorbis.dll.a' \
	-DVORBISFILE_LIBRARY='$/lib/libvorbisfile.dll.a' \
	-DVORBIS_DLL='$/bin/libvorbis-0.dll'
pushargs "$(depend_get_path zstd)" \
	-DZSTD_INCLUDE_DIR='$/include' \
	-DZSTD_LIBRARY='$/lib/libzstd.dll.a' \
	-DZSTD_DLL='$/bin/libzstd.dll'

cmake . -DCMAKE_TOOLCHAIN_FILE="$CMAKE_TOOLCHAIN" \
	-DRUN_IN_PLACE=1 -DENABLE_GETTEXT=0 \
	"${cmake_args[@]}"
make

touch $INSTALL_DIR/dummy.txt

package $pkgver
