#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=1.24.2
fetch_web "https://github.com/kcat/openal-soft/archive/refs/tags/$pkgver.tar.gz" \
	7efd383d70508587fbc146e4c508771a2235a5fc8ae05bf6fe721c20a348bd7c
unpack_tar "$pkgver.tar.gz" --strip-components=1

cmake . -DCMAKE_TOOLCHAIN_FILE="$CMAKE_TOOLCHAIN" \
	-DALSOFT_EXAMPLES=OFF -DALSOFT_UTILS=OFF
make

common_flat_tree
make DESTDIR=$INSTALL_DIR install
rm -rf $INSTALL_DIR/share
common_tidy

package $pkgver
