#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=15.2
fetch_web "https://ftp.postgresql.org/pub/source/v$pkgver/postgresql-$pkgver.tar.bz2" \
	99a2171fc3d6b5b5f56b757a7a3cb85d509a38e4273805def23941ed2b8468c7
unpack_tar "postgresql-$pkgver.tar.bz2" --strip-components=1

zlibpath=$(depend_get_path zlib)
PKG_CONFIG=/bin/false \
CFLAGS="-I$zlibpath/include" LDFLAGS="-L$zlibpath/lib" \
./configure --host=$MINGW_PREFIX --prefix=/ \
	--without-{perl,python}
make -C src/interfaces/libpq

for dir in interfaces/libpq include; do
	make -C src/$dir DESTDIR=$INSTALL_DIR install
done
mv $INSTALL_DIR/lib/libpq.{a,dll.a}
rm -rf $INSTALL_DIR/share $INSTALL_DIR/lib/*.dll
common_tidy

package $pkgver
