#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=18.4
fetch_web "https://ftp.postgresql.org/pub/source/v$pkgver/postgresql-$pkgver.tar.bz2" \
	81a81ec695fb0c7901407defaa1d2f7973617154cf27ba74e3a7ab8e64436094
unpack_tar "postgresql-$pkgver.tar.bz2" --strip-components=1
# patch sigsetjmp compatibility define
sed 's/^#ifdef __MINGW64__$/#if defined(__MINGW64__) \&\& !defined(_UCRT)/' -i src/include/c.h

zlibpath=$(depend_get_path zlib)
CFLAGS="-I$zlibpath/include" LDFLAGS="-L$zlibpath/lib" \
./configure --host=$MINGW_PREFIX --prefix=/ \
	--without-{perl,python,icu}
make -C src/interfaces/libpq

for dir in interfaces/libpq include; do
	make -C src/$dir DESTDIR=$INSTALL_DIR install
done
mv $INSTALL_DIR/lib/libpq.{a,dll.a}
rm -rf $INSTALL_DIR/share $INSTALL_DIR/lib/*.dll
common_tidy

package $pkgver
