#!/bin/bash -eu

. ./common.sh
CUSTOMOPTS[0]="full|build_full|Build with all subsystems or options"
common_init "$@"

pkgver=2.28.5
fetch_web "https://github.com/libsdl-org/SDL/releases/download/release-$pkgver/SDL2-$pkgver.tar.gz" \
	332cb37d0be20cb9541739c61f79bae5a477427d79ae85e352089afdaf6666e4
unpack_tar "SDL2-$pkgver.tar.gz"

opts=(
	-DSDL_TEST=OFF # test framework
	-DSDL_RENDER=OFF # 2D rendering
	-DSDL_AUDIO=OFF # audio output
	-DSDL_HIDAPI=OFF # USB/HID devices
)
[ $build_full -eq 1 ] && args=()
cmake -S "SDL2-$pkgver" -B . -DCMAKE_TOOLCHAIN_FILE="$CMAKE_TOOLCHAIN" \
	-DCMAKE_BUILD_TYPE=Release "${opts[@]}"
make

common_flat_tree
make DESTDIR=$INSTALL_DIR install
rm -f $INSTALL_DIR/bin/sdl2-config
common_tidy

package $pkgver
