#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=3.37.2
pkgver_year=2022
pkgver_num=3370200
fetch_web "https://www.sqlite.org/$pkgver_year/sqlite-autoconf-$pkgver_num.tar.gz" \
	4089a8d9b467537b3f246f217b84cd76e00b1d1a971fe5aca1e30e230e46b2d8
unpack_tar "sqlite-autoconf-$pkgver_num.tar.gz" --strip-components=1

CC=$MINGW_CC ./configure --host=$MINGW_PREFIX --prefix=/ \
	--disable-static-shell --disable-{fts{3,4,5},json1,rtree}
make

make DESTDIR=$INSTALL_DIR install
common_tidy

package $pkgver
