#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=3.51.1
pkgver_year=2025
pkgver_num=3510100
fetch_web "https://www.sqlite.org/$pkgver_year/sqlite-autoconf-$pkgver_num.tar.gz" \
	4f2445cd70479724d32ad015ec7fd37fbb6f6130013bd4bfbc80c32beb42b7e0
unpack_tar "sqlite-autoconf-$pkgver_num.tar.gz" --strip-components=1

./configure --host=$MINGW_PREFIX --prefix=/ \
	--disable-static-shell --disable-{fts{3,4,5},rtree}
make

make DESTDIR=$INSTALL_DIR install
common_tidy

package $pkgver
