#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=3.27.2
pkgver_year=2019
pkgver_num=3270200
fetch_web "https://www.sqlite.org/$pkgver_year/sqlite-autoconf-$pkgver_num.tar.gz" \
	50c39e85ea28b5ecfdb3f9e860afe9ba606381e21836b2849efca6a0bfe6ef6e
unpack_tar "sqlite-autoconf-$pkgver_num.tar.gz" --strip-components=1

CC=$MINGW_CC ./configure --host=$MINGW_PREFIX --prefix=/ --disable-static-shell
make

make DESTDIR=$INSTALL_DIR install
rm -rf $INSTALL_DIR/{share,lib/*.la,lib/pkgconfig} # no manpages or pkg-config on windows

package $pkgver
