#!/bin/bash -eu

. ./common.sh
CUSTOMOPTS[0]="no-asm|asmdisable|Don't build with assembly optimizations (x86 only)"
common_init "$@"

pkgver=1.2.11
fetch_web "http://zlib.net/zlib-$pkgver.tar.gz" \
	c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1
unpack_tar "zlib-$pkgver.tar.gz" --strip-components=1

# enable assembly optimizations
asmdef=
asmobj=
if [[ $asmdisable -eq 0 && "$MINGW_TYPE" = "win32" ]]; then
	cp -v contrib/asm686/match.S match.S
	asmdef="-DASMV $asmdef"
	asmobj=match.o
fi
# build using win32 makefile
make PREFIX=$MINGW_PREFIX- \
	LOC="$asmdef" OBJA=$asmobj \
	-fwin32/Makefile.gcc

make \
	DESTDIR=$INSTALL_DIR SHARED_MODE=1 \
	BINARY_PATH=/bin INCLUDE_PATH=/include LIBRARY_PATH=/lib \
	install -fwin32/Makefile.gcc
common_tidy

package $pkgver
