#!/bin/bash -eu

. ./common.sh
CUSTOMOPTS[0]="no-asm|asmdisable|Don't build with assembly optimizations"
common_init "$@"

pkgver=1.2.11
fetch_web "http://zlib.net/zlib-$pkgver.tar.gz" \
	c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1
unpack_tar "zlib-$pkgver.tar.gz" --strip-components=1

# enable assembly optimizations

if [ $asmdisable -eq 1 ]; then
	asmdef=
	asmobj=
else
	if [[ "$MINGW_PREFIX" == "x86_64-"* ]]; then
		echo "Warning: asm on x64 seems to be broken, --no-asm is recommend"
		asmfile=amd64/amd64-match.S
		asmdef=-DNO_UNDERLINE
	else
		asmfile=asm686/match.S
		asmdef=
	fi
	cp -v contrib/$asmfile match.S
	asmdef="-DASMV $asmdef"
	asmobj=match.o
fi
# build using win32 makefile
make PREFIX=$MINGW_PREFIX- \
	LOC="$asmdef" OBJA=$asmobj \
	-fwin32/Makefile.gcc -j$MAKE_JOBS

make \
	DESTDIR=$INSTALL_DIR SHARED_MODE=1 \
	BINARY_PATH=/bin INCLUDE_PATH=/include LIBRARY_PATH=/lib \
	install -fwin32/Makefile.gcc
rm -r $INSTALL_DIR/lib/pkgconfig # no pkgconfig on windows

package $pkgver
