#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=1.5.2
fetch_web "https://github.com/facebook/zstd/releases/download/v$pkgver/zstd-$pkgver.tar.gz" \
	7c42d56fac126929a6a85dbc73ff1db2411d04f104fae9bdea51305663a83fd0
unpack_tar "zstd-$pkgver.tar.gz" --strip-components=1

cmake build/cmake -DCMAKE_TOOLCHAIN_FILE="$CMAKE_TOOLCHAIN"
make

common_flat_tree
make DESTDIR=$INSTALL_DIR install
common_tidy

package $pkgver
