#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=1.5.6
fetch_web "https://github.com/facebook/zstd/releases/download/v$pkgver/zstd-$pkgver.tar.gz" \
	8c29e06cf42aacc1eafc4077ae2ec6c6fcb96a626157e0593d5e82a34fd403c1
unpack_tar "zstd-$pkgver.tar.gz" --strip-components=1

cmake build/cmake -DCMAKE_TOOLCHAIN_FILE="$CMAKE_TOOLCHAIN" \
	-DZSTD_LEGACY_SUPPORT=OFF
make

common_flat_tree
make DESTDIR=$INSTALL_DIR install
common_tidy

package $pkgver
