#!/bin/bash -eu

. ./common.sh
common_init "$@"

pkgver=1.5.5
fetch_web "https://github.com/facebook/zstd/releases/download/v$pkgver/zstd-$pkgver.tar.gz" \
	9c4396cc829cfae319a6e2615202e82aad41372073482fce286fac78646d3ee4
unpack_tar "zstd-$pkgver.tar.gz" --strip-components=1

cmake build/cmake -DCMAKE_TOOLCHAIN_FILE="$CMAKE_TOOLCHAIN"
make

common_flat_tree
make DESTDIR=$INSTALL_DIR install
common_tidy

package $pkgver
